# Generated by Django 5.2.8 on 2025-11-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'db_table': 'blocked_ips',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geolocation_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='request_log_ip_addr_7187c3_idx'), models.Index(fields=['timestamp'], name='request_log_timesta_6625f0_idx'), models.Index(fields=['path'], name='request_log_path_5a9834_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.CharField(choices=[('high_volume', 'High request volume'), ('sensitive_access', 'Access to sensitive paths'), ('multiple_sensitive', 'Multiple sensitive path accesses'), ('suspicious_pattern', 'Suspicious behavior pattern')], max_length=50)),
                ('description', models.TextField()),
                ('request_count', models.IntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'db_table': 'suspicious_ips',
                'indexes': [models.Index(fields=['ip_address', 'detected_at'], name='suspicious__ip_addr_8ebe6f_idx'), models.Index(fields=['is_resolved'], name='suspicious__is_reso_789ad0_idx')],
            },
        ),
    ]
